Repository video-platform/Video-platform, pull requests merged in 2020-06, with the labels that each got.

#3 fix : Change class name
  src/server/src/main/java/com/video/demo/config/JwtUtils.java
  src/server/src/main/java/com/video/demo/jwt/package-info.java
Labels: enhancement

#4 add : model & filters
  src/server/src/main/java/com/video/demo/config/JwtRequestFilter.java
  src/server/src/main/java/com/video/demo/model/JwtRequest.java
  src/server/src/main/java/com/video/demo/model/JwtResponse.java
  src/server/src/main/java/com/video/demo/service/JwtUserDetailsService.java
Labels: add

#5 add : setting gradle + library
  src/client/android/app/build.gradle
Labels: add

#6 Android add retrofit settings + sample
  src/client/android/app/build.gradle
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/MainActivity.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/model/ServerResponse.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/network/RetrofitApi.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/network/RetrofitBuilder.kt
  src/client/android/app/src/main/res/layout/activity_main.xml
Labels: add

#8 Feature/server/security
  src/server/.idea/gradle.xml
  src/server/.idea/misc.xml
  src/server/build.gradle
  src/server/src/main/java/com/video/demo/config/JwtRequestFilter.java
  src/server/src/main/java/com/video/demo/domain/Member.java
  src/server/src/main/java/com/video/demo/domain/TokenDto.java
  src/server/src/main/java/com/video/demo/model/JwtRequest.java
  src/server/src/main/java/com/video/demo/model/JwtResponse.java
  src/server/src/main/java/com/video/demo/repository/MemberRepository.java
  src/server/src/main/java/com/video/demo/security/JwtFactory.java
  src/server/src/main/java/com/video/demo/security/MemberContext.java
  src/server/src/main/java/com/video/demo/security/SecurityConfig.java
  src/server/src/main/java/com/video/demo/security/filter/LoginFilter.java
  src/server/src/main/java/com/video/demo/security/handlers/LoginAuthenticationSuccessHandler.java
  src/server/src/main/java/com/video/demo/security/providers/LoginAuthenticationProvider.java
  src/server/src/main/java/com/video/demo/security/tokens/PostAuthorizationToken.java
  src/server/src/main/java/com/video/demo/security/tokens/PreAuthorizationToken.java
  src/server/src/main/java/com/video/demo/service/JwtUserDetailsService.java
  src/server/src/main/java/com/video/demo/service/MemberContextService.java
  src/server/src/main/resources/application.properties
  src/server/src/test/java/com/video/demo/repository/MemberRepositoryTest.java
Labels: add

#9 Android gallery get video files
  src/client/android/app/build.gradle
  src/client/android/app/src/main/AndroidManifest.xml
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/MainActivity.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/adapter/GalleryAdapter.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/network/RetrofitBuilder.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/util/MediaStoreVideo.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/util/PermissionChecker.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/CameraPreviewActivity.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/GalleryActivity.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/MainActivity.kt
  src/client/android/app/src/main/res/layout/activity_camera_preview.xml
  src/client/android/app/src/main/res/layout/activity_gallery.xml
  src/client/android/app/src/main/res/layout/activity_main.xml
  src/client/android/app/src/main/res/layout/gallery_item_layout.xml
  src/client/android/app/src/main/res/values/strings.xml
  src/client/android/build.gradle
Labels: add

#10 Add Toolbar layout - default layout
  src/client/android/app/build.gradle
  src/client/android/app/src/main/AndroidManifest.xml
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/adapter/GalleryAdapter.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/util/MediaStoreVideo.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/util/PermissionChecker.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/GalleryActivity.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/LoginFragment.kt
  src/client/android/app/src/main/java/study/junghoon/video/clientapp/view/MainActivity.kt
  src/client/android/app/src/main/res/drawable/ic_baseline_video_call_24.xml
  src/client/android/app/src/main/res/drawable/ic_outline_account_circle_24.xml
  src/client/android/app/src/main/res/drawable/ic_outline_camera_alt_24.xml
  src/client/android/app/src/main/res/layout/activity_main.xml
  src/client/android/app/src/main/res/layout/fragment_login.xml
  src/client/android/app/src/main/res/layout/gallery_item_layout.xml
  src/client/android/app/src/main/res/menu/toolbar_item.xml
  src/client/android/app/src/main/res/values/colors.xml
  src/client/android/app/src/main/res/values/strings.xml
  src/client/android/app/src/main/res/values/styles.xml
Labels: add, duplicate
